export enum specialisationEnum {
  Geriatrician = 1,
  Dermatologist,
  InfectiousDiseaseSpecialist,
  Endocrinologist,
  Anesthesiologist,
  Cardiologist,
  HematologistOncologist,
  Allergist,
  Gastroenterologist,
  Neurologist,
  Obstetrician,
  Ophthalmologist,
  OrthopedicSurgeon,
  Otolaryngologist,
  Pediatrician,
  PhysicalMedicineAndRehabilitationSpecialist,
  Psychiatrist,
  Pulmonologist,
  Radiologist,
  Rheumatologist,
  Surgeon,
  Urologist,
  Nephrologist,
}
